### ISSUE TITLE
I'm really looking forward to your code

### ISSUE THREAD

**Issue by jilner** [liruoteng/HeavyRainRemoval#1]
I'm really looking forward to your code

**Comment by liruoteng** [comment]
Hi, I'm sorry for the delay of the code release. Since this code is related to some privacy issue from the project, it is currently pending approval. I will upload the code as soon as possible. Thanks

**Comment by liruoteng** [comment]
@jilner the code is available now. Please let me know if you have any problem running it.

**Comment by jilner** [comment]
> @jilner the code is available now. Please let me know if you have any problem running it.
Thanks very much .The test code runs correctly,and  I'm looking forward to the training and datasets.
