### ISSUE TITLE
Checkpoint file can't load

### ISSUE THREAD

**Issue by penguinbing** [liruoteng/HeavyRainRemoval#5]
There was an error when I try to load the pre-trained model. The error message is below:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 1: ordinal not in range(128)

**Comment by ShijianXu** [comment]
Try this solution [here](https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990)
The problem is caused because the author used Python2.7 to save the model.

**Comment by penguinbing** [comment]
Thank you very much. It works. @ShijianXu
